version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    networks:
      - app-network

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
